# Site settings
title: Thiago Oliveira
description: PhD student in Algorithms, Combinatorics, Optimization at Georgia Tech (ISyE). Research in decision-focused learning, sequential decision-making, and reinforcement learning, with applications in healthcare.
url: "https://thilio.github.io"
baseurl: ""

# Personal info
author:
  name: Thiago Oliveira
  email: toliveira9 at gatech dot edu
  photo: /assets/images/headshot.png
  titles:
    - title: PhD Candidate, Machine Learning
  dept: H. Milton Stewart School of Industrial and Systems Engineering
  school: Georgia Institute of Technology
  location: Atlanta, GA, USA


# Social links (leave blank or remove to hide)
social:
  google_scholar: "https://scholar.google.com/citations?user=kS1eMMYAAAAJ&hl=en"
  github: "https://github.com/thilio"
  linkedin: "https://www.linkedin.com/in/thiago-o/"
  cv: "/assets/rendercv/rendercv_output/Pandey_Himadri_CV.pdf"

# Build settings
markdown: kramdown
permalink: pretty
